services:
  app:
    build: .
    ports:
      - "1334:1334"
    depends_on:
      - db
    environment:
      SECRET_KEY: brunoyam
      LISTEN_ADDR: :1334
      DB_DSN: postgres://postgres:postgres@db:5432/gomarket
    command: ["./bin/app"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gomarket
    ports:
      - "5433:5432"